/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NotFoundRouteImport } from './routes/not-found'
import { Route as HomeRouteImport } from './routes/home'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamIndexRouteImport } from './routes/team/index'
import { Route as SponsorsIndexRouteImport } from './routes/sponsors/index'
import { Route as SignupIndexRouteImport } from './routes/signup/index'
import { Route as ScheduleIndexRouteImport } from './routes/schedule/index'
import { Route as ResetPasswordIndexRouteImport } from './routes/reset-password/index'
import { Route as ResetOtpIndexRouteImport } from './routes/reset-otp/index'
import { Route as ProshowIndexRouteImport } from './routes/proshow/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as OtpIndexRouteImport } from './routes/otp/index'
import { Route as MaintenanceIndexRouteImport } from './routes/maintenance/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as ForgotPasswordIndexRouteImport } from './routes/forgot-password/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as ComingSoonIndexRouteImport } from './routes/coming-soon/index'
import { Route as BrochureIndexRouteImport } from './routes/brochure/index'
import { Route as SignupVerifyRouteImport } from './routes/signup/verify'
import { Route as ResetPasswordVerifyRouteImport } from './routes/reset-password/verify'
import { Route as EventsEventIdRouteImport } from './routes/events/$eventId'
import { Route as TransactionsSuccessIndexRouteImport } from './routes/transactions/success/index'
import { Route as TransactionsPendingIndexRouteImport } from './routes/transactions/pending/index'
import { Route as TransactionsFailureIndexRouteImport } from './routes/transactions/failure/index'
import { Route as TransactionsVerifyTxnIdIndexRouteImport } from './routes/transactions/verify/$txnId/index'

const NotFoundRoute = NotFoundRouteImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamIndexRoute = TeamIndexRouteImport.update({
  id: '/team/',
  path: '/team/',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorsIndexRoute = SponsorsIndexRouteImport.update({
  id: '/sponsors/',
  path: '/sponsors/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupIndexRoute = SignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleIndexRoute = ScheduleIndexRouteImport.update({
  id: '/schedule/',
  path: '/schedule/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordIndexRoute = ResetPasswordIndexRouteImport.update({
  id: '/reset-password/',
  path: '/reset-password/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetOtpIndexRoute = ResetOtpIndexRouteImport.update({
  id: '/reset-otp/',
  path: '/reset-otp/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProshowIndexRoute = ProshowIndexRouteImport.update({
  id: '/proshow/',
  path: '/proshow/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const OtpIndexRoute = OtpIndexRouteImport.update({
  id: '/otp/',
  path: '/otp/',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceIndexRoute = MaintenanceIndexRouteImport.update({
  id: '/maintenance/',
  path: '/maintenance/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordIndexRoute = ForgotPasswordIndexRouteImport.update({
  id: '/forgot-password/',
  path: '/forgot-password/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComingSoonIndexRoute = ComingSoonIndexRouteImport.update({
  id: '/coming-soon/',
  path: '/coming-soon/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrochureIndexRoute = BrochureIndexRouteImport.update({
  id: '/brochure/',
  path: '/brochure/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupVerifyRoute = SignupVerifyRouteImport.update({
  id: '/signup/verify',
  path: '/signup/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordVerifyRoute = ResetPasswordVerifyRouteImport.update({
  id: '/reset-password/verify',
  path: '/reset-password/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsSuccessIndexRoute =
  TransactionsSuccessIndexRouteImport.update({
    id: '/transactions/success/',
    path: '/transactions/success/',
    getParentRoute: () => rootRouteImport,
  } as any)
const TransactionsPendingIndexRoute =
  TransactionsPendingIndexRouteImport.update({
    id: '/transactions/pending/',
    path: '/transactions/pending/',
    getParentRoute: () => rootRouteImport,
  } as any)
const TransactionsFailureIndexRoute =
  TransactionsFailureIndexRouteImport.update({
    id: '/transactions/failure/',
    path: '/transactions/failure/',
    getParentRoute: () => rootRouteImport,
  } as any)
const TransactionsVerifyTxnIdIndexRoute =
  TransactionsVerifyTxnIdIndexRouteImport.update({
    id: '/transactions/verify/$txnId/',
    path: '/transactions/verify/$txnId/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/not-found': typeof NotFoundRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/reset-password/verify': typeof ResetPasswordVerifyRoute
  '/signup/verify': typeof SignupVerifyRoute
  '/brochure/': typeof BrochureIndexRoute
  '/coming-soon/': typeof ComingSoonIndexRoute
  '/events/': typeof EventsIndexRoute
  '/forgot-password/': typeof ForgotPasswordIndexRoute
  '/login/': typeof LoginIndexRoute
  '/maintenance/': typeof MaintenanceIndexRoute
  '/otp/': typeof OtpIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/proshow/': typeof ProshowIndexRoute
  '/reset-otp/': typeof ResetOtpIndexRoute
  '/reset-password/': typeof ResetPasswordIndexRoute
  '/schedule/': typeof ScheduleIndexRoute
  '/signup/': typeof SignupIndexRoute
  '/sponsors/': typeof SponsorsIndexRoute
  '/team/': typeof TeamIndexRoute
  '/transactions/failure/': typeof TransactionsFailureIndexRoute
  '/transactions/pending/': typeof TransactionsPendingIndexRoute
  '/transactions/success/': typeof TransactionsSuccessIndexRoute
  '/transactions/verify/$txnId/': typeof TransactionsVerifyTxnIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/not-found': typeof NotFoundRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/reset-password/verify': typeof ResetPasswordVerifyRoute
  '/signup/verify': typeof SignupVerifyRoute
  '/brochure': typeof BrochureIndexRoute
  '/coming-soon': typeof ComingSoonIndexRoute
  '/events': typeof EventsIndexRoute
  '/forgot-password': typeof ForgotPasswordIndexRoute
  '/login': typeof LoginIndexRoute
  '/maintenance': typeof MaintenanceIndexRoute
  '/otp': typeof OtpIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/proshow': typeof ProshowIndexRoute
  '/reset-otp': typeof ResetOtpIndexRoute
  '/reset-password': typeof ResetPasswordIndexRoute
  '/schedule': typeof ScheduleIndexRoute
  '/signup': typeof SignupIndexRoute
  '/sponsors': typeof SponsorsIndexRoute
  '/team': typeof TeamIndexRoute
  '/transactions/failure': typeof TransactionsFailureIndexRoute
  '/transactions/pending': typeof TransactionsPendingIndexRoute
  '/transactions/success': typeof TransactionsSuccessIndexRoute
  '/transactions/verify/$txnId': typeof TransactionsVerifyTxnIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/not-found': typeof NotFoundRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/reset-password/verify': typeof ResetPasswordVerifyRoute
  '/signup/verify': typeof SignupVerifyRoute
  '/brochure/': typeof BrochureIndexRoute
  '/coming-soon/': typeof ComingSoonIndexRoute
  '/events/': typeof EventsIndexRoute
  '/forgot-password/': typeof ForgotPasswordIndexRoute
  '/login/': typeof LoginIndexRoute
  '/maintenance/': typeof MaintenanceIndexRoute
  '/otp/': typeof OtpIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/proshow/': typeof ProshowIndexRoute
  '/reset-otp/': typeof ResetOtpIndexRoute
  '/reset-password/': typeof ResetPasswordIndexRoute
  '/schedule/': typeof ScheduleIndexRoute
  '/signup/': typeof SignupIndexRoute
  '/sponsors/': typeof SponsorsIndexRoute
  '/team/': typeof TeamIndexRoute
  '/transactions/failure/': typeof TransactionsFailureIndexRoute
  '/transactions/pending/': typeof TransactionsPendingIndexRoute
  '/transactions/success/': typeof TransactionsSuccessIndexRoute
  '/transactions/verify/$txnId/': typeof TransactionsVerifyTxnIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/not-found'
    | '/events/$eventId'
    | '/reset-password/verify'
    | '/signup/verify'
    | '/brochure/'
    | '/coming-soon/'
    | '/events/'
    | '/forgot-password/'
    | '/login/'
    | '/maintenance/'
    | '/otp/'
    | '/profile/'
    | '/proshow/'
    | '/reset-otp/'
    | '/reset-password/'
    | '/schedule/'
    | '/signup/'
    | '/sponsors/'
    | '/team/'
    | '/transactions/failure/'
    | '/transactions/pending/'
    | '/transactions/success/'
    | '/transactions/verify/$txnId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/not-found'
    | '/events/$eventId'
    | '/reset-password/verify'
    | '/signup/verify'
    | '/brochure'
    | '/coming-soon'
    | '/events'
    | '/forgot-password'
    | '/login'
    | '/maintenance'
    | '/otp'
    | '/profile'
    | '/proshow'
    | '/reset-otp'
    | '/reset-password'
    | '/schedule'
    | '/signup'
    | '/sponsors'
    | '/team'
    | '/transactions/failure'
    | '/transactions/pending'
    | '/transactions/success'
    | '/transactions/verify/$txnId'
  id:
    | '__root__'
    | '/'
    | '/home'
    | '/not-found'
    | '/events/$eventId'
    | '/reset-password/verify'
    | '/signup/verify'
    | '/brochure/'
    | '/coming-soon/'
    | '/events/'
    | '/forgot-password/'
    | '/login/'
    | '/maintenance/'
    | '/otp/'
    | '/profile/'
    | '/proshow/'
    | '/reset-otp/'
    | '/reset-password/'
    | '/schedule/'
    | '/signup/'
    | '/sponsors/'
    | '/team/'
    | '/transactions/failure/'
    | '/transactions/pending/'
    | '/transactions/success/'
    | '/transactions/verify/$txnId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRoute
  NotFoundRoute: typeof NotFoundRoute
  EventsEventIdRoute: typeof EventsEventIdRoute
  ResetPasswordVerifyRoute: typeof ResetPasswordVerifyRoute
  SignupVerifyRoute: typeof SignupVerifyRoute
  BrochureIndexRoute: typeof BrochureIndexRoute
  ComingSoonIndexRoute: typeof ComingSoonIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  ForgotPasswordIndexRoute: typeof ForgotPasswordIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  MaintenanceIndexRoute: typeof MaintenanceIndexRoute
  OtpIndexRoute: typeof OtpIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  ProshowIndexRoute: typeof ProshowIndexRoute
  ResetOtpIndexRoute: typeof ResetOtpIndexRoute
  ResetPasswordIndexRoute: typeof ResetPasswordIndexRoute
  ScheduleIndexRoute: typeof ScheduleIndexRoute
  SignupIndexRoute: typeof SignupIndexRoute
  SponsorsIndexRoute: typeof SponsorsIndexRoute
  TeamIndexRoute: typeof TeamIndexRoute
  TransactionsFailureIndexRoute: typeof TransactionsFailureIndexRoute
  TransactionsPendingIndexRoute: typeof TransactionsPendingIndexRoute
  TransactionsSuccessIndexRoute: typeof TransactionsSuccessIndexRoute
  TransactionsVerifyTxnIdIndexRoute: typeof TransactionsVerifyTxnIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/not-found': {
      id: '/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/': {
      id: '/team/'
      path: '/team'
      fullPath: '/team/'
      preLoaderRoute: typeof TeamIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsors/': {
      id: '/sponsors/'
      path: '/sponsors'
      fullPath: '/sponsors/'
      preLoaderRoute: typeof SponsorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/': {
      id: '/signup/'
      path: '/signup'
      fullPath: '/signup/'
      preLoaderRoute: typeof SignupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule/': {
      id: '/schedule/'
      path: '/schedule'
      fullPath: '/schedule/'
      preLoaderRoute: typeof ScheduleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password/': {
      id: '/reset-password/'
      path: '/reset-password'
      fullPath: '/reset-password/'
      preLoaderRoute: typeof ResetPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-otp/': {
      id: '/reset-otp/'
      path: '/reset-otp'
      fullPath: '/reset-otp/'
      preLoaderRoute: typeof ResetOtpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proshow/': {
      id: '/proshow/'
      path: '/proshow'
      fullPath: '/proshow/'
      preLoaderRoute: typeof ProshowIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otp/': {
      id: '/otp/'
      path: '/otp'
      fullPath: '/otp/'
      preLoaderRoute: typeof OtpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance/': {
      id: '/maintenance/'
      path: '/maintenance'
      fullPath: '/maintenance/'
      preLoaderRoute: typeof MaintenanceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password/': {
      id: '/forgot-password/'
      path: '/forgot-password'
      fullPath: '/forgot-password/'
      preLoaderRoute: typeof ForgotPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coming-soon/': {
      id: '/coming-soon/'
      path: '/coming-soon'
      fullPath: '/coming-soon/'
      preLoaderRoute: typeof ComingSoonIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brochure/': {
      id: '/brochure/'
      path: '/brochure'
      fullPath: '/brochure/'
      preLoaderRoute: typeof BrochureIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/verify': {
      id: '/signup/verify'
      path: '/signup/verify'
      fullPath: '/signup/verify'
      preLoaderRoute: typeof SignupVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password/verify': {
      id: '/reset-password/verify'
      path: '/reset-password/verify'
      fullPath: '/reset-password/verify'
      preLoaderRoute: typeof ResetPasswordVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/success/': {
      id: '/transactions/success/'
      path: '/transactions/success'
      fullPath: '/transactions/success/'
      preLoaderRoute: typeof TransactionsSuccessIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/pending/': {
      id: '/transactions/pending/'
      path: '/transactions/pending'
      fullPath: '/transactions/pending/'
      preLoaderRoute: typeof TransactionsPendingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/failure/': {
      id: '/transactions/failure/'
      path: '/transactions/failure'
      fullPath: '/transactions/failure/'
      preLoaderRoute: typeof TransactionsFailureIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/verify/$txnId/': {
      id: '/transactions/verify/$txnId/'
      path: '/transactions/verify/$txnId'
      fullPath: '/transactions/verify/$txnId/'
      preLoaderRoute: typeof TransactionsVerifyTxnIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRoute,
  NotFoundRoute: NotFoundRoute,
  EventsEventIdRoute: EventsEventIdRoute,
  ResetPasswordVerifyRoute: ResetPasswordVerifyRoute,
  SignupVerifyRoute: SignupVerifyRoute,
  BrochureIndexRoute: BrochureIndexRoute,
  ComingSoonIndexRoute: ComingSoonIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  ForgotPasswordIndexRoute: ForgotPasswordIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  MaintenanceIndexRoute: MaintenanceIndexRoute,
  OtpIndexRoute: OtpIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  ProshowIndexRoute: ProshowIndexRoute,
  ResetOtpIndexRoute: ResetOtpIndexRoute,
  ResetPasswordIndexRoute: ResetPasswordIndexRoute,
  ScheduleIndexRoute: ScheduleIndexRoute,
  SignupIndexRoute: SignupIndexRoute,
  SponsorsIndexRoute: SponsorsIndexRoute,
  TeamIndexRoute: TeamIndexRoute,
  TransactionsFailureIndexRoute: TransactionsFailureIndexRoute,
  TransactionsPendingIndexRoute: TransactionsPendingIndexRoute,
  TransactionsSuccessIndexRoute: TransactionsSuccessIndexRoute,
  TransactionsVerifyTxnIdIndexRoute: TransactionsVerifyTxnIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
